include ${ROOTDIR}/build/config/env.mk

SUBMODULECHILD_PATH = ${ROOTDIR}/modules/$(MODULE)/${SUBMODULE}
SUBMODULECHILD_SRC_INC_PATH = $(SUBMODULECHILD_PATH)/include
SUBMODULECHILD_SRC_PATH = $(SUBMODULECHILD_PATH)/src

SUBMODULECHILD_OUTPUT_PATH = $(OUTPUTS_DIR)/$(MODULE)/${MODULE_VERSION}/$(SUBMODULE)

SUBMODULECHILD_OUTPUT_TMP_PATH = $(SUBMODULECHILD_OUTPUT_PATH)/.tmp
SUBMODULECHILD_OUTPUT_INC_PATH = $(SUBMODULECHILD_OUTPUT_PATH)/include/${SUBMODULE}
SUBMODULECHILD_OUTPUT_LIB_PATH = $(SUBMODULECHILD_OUTPUT_PATH)/lib
SUBMODULECHILD_OUTPUT_BIN_PATH = $(SUBMODULECHILD_OUTPUT_PATH)/bin
SUBMODULECHILD_OUTPUT_CFG_PATH = $(SUBMODULECHILD_OUTPUT_PATH)/etc

SUBMODULECHILD_TMP2_OBJS = $(patsubst %.c, %.o, $(SUBMODULECHILD_SRC))
SUBMODULECHILD_OBJS = $(patsubst %.cpp, %.o, $(SUBMODULECHILD_TMP2_OBJS))
SUBMODULECHILD_OUTPUT_OBJS = $(SUBMODULECHILD_OBJS:%=$(SUBMODULECHILD_OUTPUT_TMP_PATH)/%)

include $(ROOTDIR)/build/compilation/compilation.mk

prepare_submodulechild:
	$(MKDIR) $(SUBMODULECHILD_OUTPUT_TMP_PATH)
	$(MKDIR) $(SUBMODULECHILD_OUTPUT_INC_PATH)
	$(MKDIR) $(SUBMODULECHILD_OUTPUT_LIB_PATH)
	$(MKDIR) $(SUBMODULECHILD_OUTPUT_BIN_PATH)
	$(MKDIR) $(SUBMODULECHILD_OUTPUT_CFG_PATH)

build_submodulechild: $(SUBMODULECHILD_TMP_TARGET)

install_submodulechild:
	if [ -d ${SUBMODULECHILD_SRC_INC_PATH} ]; then \
		$(CP) ${SUBMODULECHILD_SRC_INC_PATH}/* ${SUBMODULECHILD_OUTPUT_INC_PATH}; \
	fi
	$(CP) ${SUBMODULECHILD_TMP_TARGET} ${SUBMODULECHILD_TARGET}

submodulechild_build_prerequisites = prepare_submodulechild build_submodulechild install_submodulechild

submodulechild_build: $(submodulechild_build_prerequisites)

submodulechild_clean:
	rm -rf $(SUBMODULECHILD_OUTPUT_PATH)
