ifeq (${SUBMODULECHILD_CLASS}, app)

SUBMODULECHILD_DEPS_PATH = ${SUBMODULECHILD_DEPS:%=${OUTPUTS_DIR}/%/lib}
SUBMODULECHILD_DEPS_OUTPUT_LIBS_DIRS = $(foreach DEP, ${SUBMODULECHILD_DEPS}, ${OUTPUTS_DIR}/${DEP}/lib/)
SUBMODULECHILD_DEPS_LIBS = $(foreach DEP, ${SUBMODULECHILD_DEPS}, $(subst lib,,$(firstword $(subst /, ,${DEP}))))
SUBMODULECHILD_LD_FLAGS = ${SUBMODULECHILD_DEPS_LIBS:%=-l%}
SUBMODULECHILD_LD_FLAGS += ${SUBMODULECHILD_DEPS_OUTPUT_LIBS_DIRS:%=-L%}

SUBMODULECHILD_TMP_TARGET = ${SUBMODULECHILD:%=${SUBMODULECHILD_OUTPUT_TMP_PATH}/%}


${SUBMODULECHILD_TMP_TARGET}:${SUBMODULECHILD_OUTPUT_OBJS}
	$(GCC) -o $@ $^ ${SUBMODULECHILD_LD_FLAGS}

SUBMODULECHILD_TARGET = ${SUBMODULECHILD_OUTPUT_BIN_PATH}/${SUBMODULECHILD}

endif
