MODULE_DEPS_MODULES = ${MODULE_DEPS} ${MODULE_SLIB_DEPS} ${MODULE_DLIB_DEPS}
MODULE_INCLUDE_FLAGS = -I${MODULE_SRC_INC_PATH} -I${MODULE_SRC_PATH} $(MODULE_DEPS_MODULES:%=-I${OUTPUTS_DIR}/%/include) $(3RD_DEPS:%=-I${OUTPUTS_DIR}/3rd/${3RD_VERSION}/%/include)

GCC_OPTION_FLAGS = -trigraphs -g
GCC_OPTION_FLAGS += ${GCC_FLAGS}

${MODULE_OUTPUT_TMP_PATH}/%.o: ${MODULE_SRC_PATH}/%.c
	$(GCC) ${GCC_OPTION_FLAGS} -c $^ -o $@ ${MODULE_INCLUDE_FLAGS}

${MODULE_OUTPUT_TMP_PATH}/%.s: ${MODULE_SRC_PATH}/%.c
	$(GCC) ${GCC_OPTION_FLAGS} -S $^ -o $@ ${MODULE_INCLUDE_FLAGS}

${MODULE_OUTPUT_TMP_TEST_PATH}/%.o: ${MODULE_SRC_TEST_PATH}/%.c
	$(GCC) ${GCC_OPTION_FLAGS} -c $^ -o $@ ${MODULE_INCLUDE_FLAGS}

${MODULE_OUTPUT_TMP_PATH}/%.o: ${MODULE_SRC_PATH}/%.cpp
	$(GXX) -c $^ -o $@ ${MODULE_INCLUDE_FLAGS}

${MODULE_OUTPUT_TMP_TEST_PATH}/%.o: ${MODULE_SRC_TEST_PATH}/%.cpp
	$(GXX) -c $^ -o $@ ${MODULE_INCLUDE_FLAGS}

SUBMODULECHILD_DEPS_MODULES = ${SUBMODULECHILD_DEPS} ${SUBMODULECHILD_SLIB_DEPS} ${SUBMODULECHILD_DLIB_DEPS}
SUBMODULECHILD_INCLUDE_FLAGS = -I${SUBMODULECHILD_SRC_INC_PATH} -I${SUBMODULECHILD_SRC_PATH} $(SUBMODULECHILD_DEPS_MODULES:%=-I${OUTPUTS_DIR}/%/include)

${SUBMODULECHILD_OUTPUT_TMP_PATH}/%.o: ${SUBMODULECHILD_SRC_PATH}/%.c
	$(GCC) ${GCC_OPTION_FLAGS} -c $^ -o $@ ${SUBMODULECHILD_INCLUDE_FLAGS}

${SUBMODULECHILD_OUTPUT_TMP_PATH}/%.o: ${SUBMODULECHILD_SRC_PATH}/%.cpp
	$(GXX) -c $^ -o $@ ${SUBMODULECHILD_INCLUDE_FLAGS}
