MODULE_DEPS_MODULES = ${MODULE_DEPS} ${MODULE_SLIB_DEPS} ${MODULE_DLIB_DEPS}
MODULE_INCLUDE_FLAGS = -I${MODULE_SRC_INC_PATH} $(MODULE_DEPS_MODULES:%=-I${OUTPUTS_DIR}/%/include)

${MODULE_OUTPUT_TMP_PATH}/%.o: ${MODULE_SRC_PATH}/%.c
	$(GCC) -c $^ -o $@ ${MODULE_INCLUDE_FLAGS}

${MODULE_OUTPUT_TMP_TEST_PATH}/%.o: ${MODULE_SRC_TEST_PATH}/%.c
	$(GCC) -c $^ -o $@ ${MODULE_INCLUDE_FLAGS}

SUBMODULECHILD_DEPS_MODULES = ${SUBMODULECHILD_DEPS} ${SUBMODULECHILD_SLIB_DEPS} ${SUBMODULECHILD_DLIB_DEPS}
SUBMODULECHILD_INCLUDE_FLAGS = -I${SUBMODULECHILD_SRC_INC_PATH} $(SUBMODULECHILD_DEPS_MODULES:%=-I${OUTPUTS_DIR}/%/inc)

${SUBMODULECHILD_OUTPUT_TMP_PATH}/%.o: ${SUBMODULECHILD_SRC_PATH}/%.c
	$(GCC) -c $^ -o $@ ${SUBMODULECHILD_INCLUDE_FLAGS}

